# Generated by Django 4.2.13 on 2024-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=50)),
                ('bDescription', models.CharField(max_length=300)),
            ],
        ),
    ]
